# -*- coding: utf-8 -*-
"""Guia ejercicios 1 - variables, tipos de datos, condicionales , ciclos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IoyPoUTbVOvmoPPG0ea8YvWDZX0960IW

# Tipos de Datos y Variables

1. Crea un programa que almacene tu nombre, edad y estatura, y luego imprima una presentación con esa información.
2.	Declara tres variables: una booleana que indique si tienes hambre, un número entero con la cantidad de horas desde tu última comida y un float con el nivel de hambre del 1.0 al 10.0. Imprime un mensaje distinto según el nivel de hambre.
3.	Pide al usuario que ingrese su año de nacimiento (como entero) y calcula su edad aproximada. Usa una variable bool para indicar si es mayor de edad y muestra el resultado.
4.	Declara una variable precio_base (float), un descuento (int, porcentaje) y un producto (string). Muestra el precio final aplicando el descuento.
5.	Dadas tres variables: nota1, nota2 y nota3 (float), calcula el promedio y declara una variable booleana que indique si el estudiante aprobó (nota mínima: 4.0).
6.	Declara una variable string que almacene una frase y calcula cuántas palabras contiene. Usa otra variable bool para indicar si la frase tiene más de 10 palabras.
7.	Crea una calculadora de IMC (Índice de Masa Corporal) con variables peso (float en kg) y altura (float en metros). Declara una variable booleana que indique si el resultado es saludable (IMC entre 18.5 y 24.9).
8.	Simula un sistema de entrada a un evento. Declara una variable edad (int), tiene_entrada (bool) y nombre_evento (str). Imprime si puede o no entrar.
9.	Declara una variable con tu nombre completo. Extrae solo el primer nombre y crea una nueva variable que almacene el saludo “Hola, [nombre]”.
10.	Declara tres precios de productos (float), súmalos y verifica si el total supera un presupuesto dado (int). Muestra un mensaje distinto según el caso.
11.	Crea una pequeña encuesta con tres preguntas. Almacena las respuestas en variables de tipo string y muestra un resumen final, donde cada línea esté numerada.
12.	Crea un programa que calcule el total a pagar por una compra, incluyendo IVA (usa una variable iva como porcentaje float). Valida con una variable booleana si el monto supera los $100.000.
13.	Declara una variable string con una contraseña. Solicita al usuario que intente adivinarla. Usa una variable booleana para indicar si el acceso fue concedido o no.
14.	Dado un número decimal (float), muestra su parte entera (int) y la parte decimal por separado (float).
15.	Simula una trivia: almacena 3 preguntas con sus respuestas correctas (strings o int), permite al usuario responder, y usa variables booleanas para verificar si acertó. Muestra un puntaje final.
16.	Declara una variable que almacene una temperatura en grados Celsius (float), convierte ese valor a Fahrenheit y a Kelvin, usando variables nuevas. Muestra todos los resultados.
17.	Simula una compra online: pide al usuario el nombre de un producto (str), su precio (float), si tiene descuento (bool) y el número de unidades (int). Calcula y muestra el total a pagar con o sin descuento.

# Uso de PRINT

1.	Imprime una frase simple que diga: “¡Hola, mundo!”
2.	Crea dos variables (nombre, edad) y usa print() para mostrar un mensaje concatenando ambas: “Me llamo [nombre] y tengo [edad] años.”
3.	Muestra una tabla de 3 columnas (Producto, Precio, Stock) usando \t para alinear columnas con tabulaciones.
4.	Imprime una frase en varias líneas usando \n, como si fuera un poema de tres versos.
5.	Usa print() con múltiples argumentos separados por comas para mostrar: nombre, edad y ciudad, asegurándote de que haya espacios automáticamente.
6.	Declara una variable string con comillas dobles adentro (ej: Ella dijo “Hola”), e imprime el texto respetando las comillas.
7.	Crea una línea decorada con asteriscos antes y después de un mensaje central, por ejemplo: ***** Bienvenido *****. Usa print() más de una vez si es necesario.
8.	Imprime un texto largo dividido en varias líneas con print() múltiples veces, sin usar \n.
9.	Declara tres variables numéricas e imprime una operación matemática mostrando tanto la operación como el resultado: ej. 3 + 4 = 7
10.	Usa un f-string para imprimir una temperatura como: "La temperatura actual es de 23.5°C" usando una variable temp.
11.	Imprime una dirección usando saltos de línea para que el formato quede como una carta tradicional: nombre, calle, ciudad, país.
12.	Muestra el resultado de una división como parte de una frase, usando un f-string y limitando el resultado a 2 decimales.
13.	Declara una variable booleana es_mayor y muestra una salida que diga: “¿Es mayor de edad?: True” (o False según el valor).
14.	Crea un mensaje que combine texto y emojis, como: "Tu calificación fue excelente 😄"
15.	Usa print() para mostrar una lista de tareas numeradas del 1 al 5, cada una en una línea distinta.
16.	Imprime una expresión compleja con múltiples operadores lógicos y matemáticos, mostrando el resultado final como parte del mensaje.
17.	Haz que el programa imprima una barra de progreso simple, como: [#####-----] 50%, usando concatenación de strings y símbolos.

# Condicionales

1.	Pide al usuario que ingrese un número entero y muestra si es positivo.
2.	Solicita la edad de una persona y muestra un mensaje que diga si es menor o mayor de edad.
3.	Pide una contraseña y verifica si coincide con una contraseña predefinida. Muestra un mensaje de acceso concedido o denegado.
4.	Solicita al usuario un número entero. Si es par, muestra “Es par”, si no, muestra “Es impar”.
5.	Pide al usuario que ingrese su nota final (entre 1.0 y 7.0). Muestra: “Reprobado” si es menor a 4.0, “Aprobado” si es mayor o igual a 4.0.
6.	Crea un sistema de validación para ingresar a una fiesta: pide edad y si tiene entrada (sí o no). Permite el ingreso solo si tiene ambos requisitos.
7.	Pide una temperatura (float) y muestra si hace frío (<10), templado (entre 10 y 25), o calor (>25). Usa if, elif y else.
8.	Solicita al usuario un número del 1 al 7 y muestra qué día de la semana corresponde (1 = lunes, 7 = domingo). Usa elif.
9.	Pide dos números al usuario y determina cuál es el mayor. Si son iguales, muestra un mensaje indicando que son iguales.
10.	Crea un programa que calcule si un año es bisiesto. Un año es bisiesto si es divisible por 4, pero no por 100, excepto si también es divisible por 400.
11.	Solicita el nombre de usuario y si es igual a “admin”, muestra un mensaje especial de bienvenida. Si no, muestra un saludo genérico.
12.	Simula una calculadora: pide dos números y una operación (+, -, , /). Usa condicionales para realizar la operación correspondiente.
13.	Pide al usuario que ingrese una nota. Según el valor, muestra: “Insuficiente” (<4), “Suficiente” (4–5), “Bueno” (5–6), “Excelente” (6–7). Usa elif.
14.	Pide al usuario su edad y si tiene licencia. Solo si tiene ambas condiciones puede conducir. Usa un if anidado.
15.	Solicita una clave secreta. Si la clave es incorrecta tres veces, muestra un mensaje de “Acceso bloqueado”. Usa if dentro de un control de intentos.
16.	Pide al usuario que ingrese un número del 1 al 12. Muestra a qué mes del año corresponde. Si no está en el rango, muestra “Mes inválido”.
17.	Pide al usuario un número. Si está entre 1 y 100 (inclusive), muestra “Número válido”. Si no, muestra “Número fuera de rango”.

# Ciclos

1.	Imprime los números del 1 al 10 usando un ciclo for.
2.	Imprime los números pares del 2 al 20 usando un ciclo for.
3.	Dado un string, recorre cada letra con un for y muestra cada una en una línea distinta.
4.	Usa un ciclo for para calcular la suma de los primeros 100 números enteros positivos.
5.	Imprime una tabla de multiplicar (del 1 al 10) para un número ingresado por el usuario.
6.	Crea un patrón de triángulo con asteriscos de altura 5, usando un for anidado. Ejemplo:


```
*
**
***
****
*****
```

7.	Imprime todas las combinaciones posibles entre dos listas: una de colores y otra de prendas. Usa for anidados.
8.	Pide 5 nombres al usuario y guárdalos en una lista. Luego, recórrela con un for para saludarlos uno por uno.
9.	Dibuja una matriz de 3x3 con números del 1 al 9 usando for anidados.
10.	Imprime los números del 10 al 1 usando un ciclo while.
11.	Solicita contraseñas al usuario hasta que escriba la correcta. Usa un while con condición.
12.	Pide números al usuario hasta que escriba uno negativo. Al final, muestra la suma total de todos los números positivos ingresados.
13.	Simula un menú interactivo con opciones del 1 al 4 y una opción 0 para salir. El menú debe repetirse hasta que el usuario elija salir.
14.	Pide al usuario un número y muestra si es primo. Usa un ciclo while para verificar los divisores.
15.	Crea un juego donde el usuario tiene que adivinar un número secreto del 1 al 10. Da pistas si el número ingresado es mayor o menor, hasta acertar.
16.	Dibuja un rectángulo de caracteres # con dimensiones dadas por el usuario (alto y ancho), usando while anidado o for anidado.
17.	Genera un tablero de ajedrez de 8x8 alternando # y espacio, como:


```
# # # #
 # # # #
# # # #
 # # # #
...
```
"""